using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DisneyLibWin
{
    public class Restaurant
    {
        public Restaurant() { }

        public Restaurant(int entityId, string name)
        { this.EntityId = entityId; Name = name; }

        public int EntityId { get; set; }
        public string Name { get; set; }

        public override string ToString()
        {
            return $"{Name} - Id: {EntityId}";
        }


        public static List<Restaurant> GetRestaurants()
        {
            var returnList = new List<Restaurant>(500);

            returnList.Add(new Restaurant(90001216, "50's Prime Time Café"));
            returnList.Add(new Restaurant(90001212, "1900 Park Fare"));
            returnList.Add(new Restaurant(90001220, "ABC Commissary"));
            returnList.Add(new Restaurant(18451303, "AbracadaBar"));
            returnList.Add(new Restaurant(17736017, "Afternoon Tea at Garden View Tea Room"));
            returnList.Add(new Restaurant(90002066, "Akershus Royal Banquet Hall"));
            returnList.Add(new Restaurant(90001228, "Ale & Compass Lounge"));
            returnList.Add(new Restaurant(18733814, "Ale & Compass Restaurant"));
            returnList.Add(new Restaurant(90002426, "Aloha Isle"));
            returnList.Add(new Restaurant(16012973, "AMC® Disney Springs 24 Dine-In Theatres"));
            returnList.Add(new Restaurant(18415488, "Amorette's Patisserie"));
            returnList.Add(new Restaurant(18419410, "Ample Hills Creamery"));
            returnList.Add(new Restaurant(90001231, "Anaheim Produce"));
            returnList.Add(new Restaurant(90001233, "Anandapur Ice Cream Truck"));
            returnList.Add(new Restaurant(90001546, "Arctic Expeditions"));
            returnList.Add(new Restaurant(18424522, "AristoCrêpes"));
            returnList.Add(new Restaurant(90001248, "Artist Point"));
            returnList.Add(new Restaurant(90002219, "The Artist's Palette"));
            returnList.Add(new Restaurant(90002444, "Auntie Gravity's Galactic Goodies"));
            returnList.Add(new Restaurant(90001258, "Avalunch"));
            returnList.Add(new Restaurant(90001260, "Backlot Express"));
            returnList.Add(new Restaurant(214152, "Backstretch Pool Bar"));
            returnList.Add(new Restaurant(90001264, "Barefoot Pool Bar"));
            returnList.Add(new Restaurant(18744584, "BaseLine Tap House"));
            returnList.Add(new Restaurant(18424520, "B.B. Wolf's Sausage Co."));
            returnList.Add(new Restaurant(32482, "Beach Club Marketplace"));
            returnList.Add(new Restaurant(90001272, "Beaches & Cream Soda Shop"));
            returnList.Add(new Restaurant(90001270, "Beaches Pool Bar & Grill"));
            returnList.Add(new Restaurant(90001278, "Belle Vue Lounge"));
            returnList.Add(new Restaurant(16660079, "Be Our Guest Restaurant"));
            returnList.Add(new Restaurant(90001292, "Biergarten Restaurant"));
            returnList.Add(new Restaurant(90001294, "Big River Grille & Brewing Works"));
            returnList.Add(new Restaurant(18419288, "Blaze Fast-Fire'd Pizza"));
            returnList.Add(new Restaurant(17561004, "Block & Hans"));
            returnList.Add(new Restaurant(90001311, "BoardWalk Bakery"));
            returnList.Add(new Restaurant(90001315, "BoardWalk Joe's Marvelous Margaritas"));
            returnList.Add(new Restaurant(17936197, "The BOATHOUSE®: Great Food, Waterfront Dining, Dream Boats™"));
            returnList.Add(new Restaurant(90002448, "Boatwright's Dining Hall"));
            returnList.Add(new Restaurant(90001320, "Boma - Flavors of Africa"));
            returnList.Add(new Restaurant(90001324, "Bongos Cuban Café™"));
            returnList.Add(new Restaurant(16736787, "Bongos Cuban Café™ Express"));
            returnList.Add(new Restaurant(90001333, "Cabana Bar and Beach Club"));
            returnList.Add(new Restaurant(230222, "Cafe Rix"));
            returnList.Add(new Restaurant(18687685, "Cake Decorating Experience at Amorette's Patisserie"));
            returnList.Add(new Restaurant(90001336, "California Grill"));
            returnList.Add(new Restaurant(90001340, "California Grill Lounge"));
            returnList.Add(new Restaurant(17564463, "Capa"));
            returnList.Add(new Restaurant(18702062, "Capa Bar"));
            returnList.Add(new Restaurant(90001347, "Cape May Cafe"));
            returnList.Add(new Restaurant(13219, "Cape Town Lounge and Wine Bar"));
            returnList.Add(new Restaurant(90001357, "Capt. Cook's"));
            returnList.Add(new Restaurant(90002456, "Caravan Road"));
            returnList.Add(new Restaurant(90002458, "Casey's Corner"));
            returnList.Add(new Restaurant(90001365, "Catalina Eddie's"));
            returnList.Add(new Restaurant(18663363, "Celebration at the Top - Savor, Sip, and Sparkle"));
            returnList.Add(new Restaurant(18710185, "Centertown Bar"));
            returnList.Add(new Restaurant(18710186, "Centertown Food Truck"));
            returnList.Add(new Restaurant(18710180, "Centertown Pavilion"));
            returnList.Add(new Restaurant(18718374, "Character Dining"));
            returnList.Add(new Restaurant(18427314, "Chef Art Smith's Homecomin'"));
            returnList.Add(new Restaurant(90001369, "Chef Mickey's"));
            returnList.Add(new Restaurant(90001373, "Chefs de France"));
            returnList.Add(new Restaurant(90002484, "Cheshire Café"));
            returnList.Add(new Restaurant(18394590, "Chips & Slices"));
            returnList.Add(new Restaurant(18463740, "Choza de Margarita"));
            returnList.Add(new Restaurant(177658, "The Chuck Wagon"));
            returnList.Add(new Restaurant(90002464, "Cinderella's Royal Table"));
            returnList.Add(new Restaurant(90001378, "Cítricos"));
            returnList.Add(new Restaurant(90001382, "Cítricos Chef's Domain"));
            returnList.Add(new Restaurant(58508, "Cítricos Lounge"));
            returnList.Add(new Restaurant(18459575, "Coca-Cola Store Rooftop Beverage Bar"));
            returnList.Add(new Restaurant(90001399, "Columbia Harbour House"));
            returnList.Add(new Restaurant(293614, "Contempo Café"));
            returnList.Add(new Restaurant(90001407, "Contemporary Grounds"));
            returnList.Add(new Restaurant(98576, "Cookes of Dublin"));
            returnList.Add(new Restaurant(90002227, "Cooling Hut"));
            returnList.Add(new Restaurant(90002468, "Cool Ship"));
            returnList.Add(new Restaurant(90001416, "Coral Reef Restaurant"));
            returnList.Add(new Restaurant(90002470, "Cosmic Ray's Starlight Café"));
            returnList.Add(new Restaurant(90001423, "Courtyard Pool Bar"));
            returnList.Add(new Restaurant(362428, "Cove Bar"));
            returnList.Add(new Restaurant(18058385, "Creature Comforts"));
            returnList.Add(new Restaurant(90001427, "Crepes des Chefs de France"));
            returnList.Add(new Restaurant(90001433, "Crew's Cup Lounge"));
            returnList.Add(new Restaurant(90001437, "Crockett's Tavern"));
            returnList.Add(new Restaurant(90002660, "The Crystal Palace"));
            returnList.Add(new Restaurant(18424498, "The Daily Poutine"));
            returnList.Add(new Restaurant(90001443, "Dawa Bar"));
            returnList.Add(new Restaurant(247904, "The Diamond Horseshoe"));
            returnList.Add(new Restaurant(18185692, "Dine with an Imagineer at Cítricos"));
            returnList.Add(new Restaurant(17736019, "Dine with an Imagineer at The Hollywood Brown Derby"));
            returnList.Add(new Restaurant(18046440, "Dine with Animal Specialist"));
            returnList.Add(new Restaurant(90002472, "Dino-Bite Snacks"));
            returnList.Add(new Restaurant(18398149, "Disney Early Morning Magic - Fantasyland"));
            returnList.Add(new Restaurant(18470903, "Disney Festival of Fantasy Parade Dining Package"));
            returnList.Add(new Restaurant(18676533, "Disney Food Trucks"));
            returnList.Add(new Restaurant(18613012, "Disney on Broadway Concert Series Dining Package"));
            returnList.Add(new Restaurant(17019212, "Disney Resorts In-Room Dining"));
            returnList.Add(new Restaurant(17019208, "Disney Resorts Private Dining"));
            returnList.Add(new Restaurant(17736023, "Disney's Perfectly Princess Tea"));
            returnList.Add(new Restaurant(3809, "Disney's Spirit of Aloha Dinner Show"));
            returnList.Add(new Restaurant(18396826, "D-Luxe Burger"));
            returnList.Add(new Restaurant(90001951, "Dockside Diner"));
            returnList.Add(new Restaurant(18061966, "Dockside Margaritas"));
            returnList.Add(new Restaurant(13259344, "Drinkwallah"));
            returnList.Add(new Restaurant(16472608, "The Drop Off Pool Bar"));
            returnList.Add(new Restaurant(90001465, "Earl Of Sandwich®"));
            returnList.Add(new Restaurant(18472966, "The Edison"));
            returnList.Add(new Restaurant(25098, "Eight Spoon Café"));
            returnList.Add(new Restaurant(90001477, "Electric Umbrella"));
            returnList.Add(new Restaurant(90001482, "End Zone Food Court"));
            returnList.Add(new Restaurant(18808553, "Enzo's Hideaway"));
            returnList.Add(new Restaurant(18041951, "Erin McKenna's Bakery NYC"));
            returnList.Add(new Restaurant(90001523, "ESPN Club"));
            returnList.Add(new Restaurant(244731, "ESPN Wide World of Sports Grill"));
            returnList.Add(new Restaurant(90001527, "Everything POP Shopping & Dining"));
            returnList.Add(new Restaurant(90001531, "Fairfax Fare"));
            returnList.Add(new Restaurant(18690902, "Fantasmic! Dessert & VIP Viewing Experience"));
            returnList.Add(new Restaurant(17736028, "Fantasmic! Dining Package"));
            returnList.Add(new Restaurant(18123662, "Ferrytale Fireworks: A Sparkling Dessert Cruise"));
            returnList.Add(new Restaurant(248784, "Fife & Drum Tavern"));
            returnList.Add(new Restaurant(18436545, "Fireworks Dessert Party at Tomorrowland Terrace"));
            returnList.Add(new Restaurant(18436543, "Fireworks Dessert Party with Plaza Garden Viewing"));
            returnList.Add(new Restaurant(90002524, "Flame Tree Barbecue"));
            returnList.Add(new Restaurant(17411626, "Florida Snow Company"));
            returnList.Add(new Restaurant(90001548, "Flying Fish"));
            returnList.Add(new Restaurant(90001456, "The Fountain"));
            returnList.Add(new Restaurant(90001564, "Fountain View"));
            returnList.Add(new Restaurant(90001568, "Fresh Mediterranean Market"));
            returnList.Add(new Restaurant(114690, "The Friar's Nook"));
            returnList.Add(new Restaurant(18436515, "Frontera Cocina"));
            returnList.Add(new Restaurant(131027, "The Front Porch"));
            returnList.Add(new Restaurant(113666, "Frostbite Freddy's Frozen Freshments"));
            returnList.Add(new Restaurant(18686475, "Frozen Ever After Dessert Party at Epcot World Showcase"));
            returnList.Add(new Restaurant(90001577, "Funnel Cake"));
            returnList.Add(new Restaurant(248601, "Funnel Cake Cart"));
            returnList.Add(new Restaurant(90002237, "The Garden Grill"));
            returnList.Add(new Restaurant(90001728, "Garden Grove"));
            returnList.Add(new Restaurant(18548256, "Garden Rocks Dining Packages"));
            returnList.Add(new Restaurant(90002241, "Garden View Tea Room"));
            returnList.Add(new Restaurant(90001583, "Gasparilla Island Grill"));
            returnList.Add(new Restaurant(16767318, "Gaston's Tavern"));
            returnList.Add(new Restaurant(90001704, "Gelati"));
            returnList.Add(new Restaurant(18663158, "Geyser Point Bar & Grill"));
            returnList.Add(new Restaurant(90001710, "Ghirardelli® Ice Cream & Chocolate Shop"));
            returnList.Add(new Restaurant(90002530, "Golden Oak Outpost"));
            returnList.Add(new Restaurant(17855368, "Good Morning Breakfast with Goofy and His Pals"));
            returnList.Add(new Restaurant(90001718, "Good's Food to Go"));
            returnList.Add(new Restaurant(90001724, "Grand Floridian Cafe"));
            returnList.Add(new Restaurant(90002209, "Grandstand Spirits"));
            returnList.Add(new Restaurant(90002243, "Gurgling Suitcase"));
            returnList.Add(new Restaurant(17581448, "Häagen-Dazs® at Disney Springs West Side"));
            returnList.Add(new Restaurant(90001734, "Happy Landings Ice Cream"));
            returnList.Add(new Restaurant(90001736, "Harambe Fruit Market"));
            returnList.Add(new Restaurant(18088970, "Harambe Market"));
            returnList.Add(new Restaurant(18569312, "Highway in the Sky Dine Around"));
            returnList.Add(new Restaurant(90002245, "The Hollywood Brown Derby"));
            returnList.Add(new Restaurant(17571157, "The Hollywood Brown Derby Lounge"));
            returnList.Add(new Restaurant(90001748, "Hollywood Scoops"));
            returnList.Add(new Restaurant(90001744, "Hollywood & Vine"));
            returnList.Add(new Restaurant(80010856, "Hoop-Dee-Doo Musical Revue"));
            returnList.Add(new Restaurant(90001754, "House of Blues Restaurant & Bar"));
            returnList.Add(new Restaurant(90001758, "Hurricane Hanna's Waterside Bar and Grill"));
            returnList.Add(new Restaurant(90001303, "I.C. Expeditions"));
            returnList.Add(new Restaurant(90002012, "Il Mulino"));
            returnList.Add(new Restaurant(16724469, "Il Mulino Lounge"));
            returnList.Add(new Restaurant(90001762, "Intermission Food Court"));
            returnList.Add(new Restaurant(18710187, "Island Markets"));
            returnList.Add(new Restaurant(90002640, "Isle of Java"));
            returnList.Add(new Restaurant(108863, "Java Bar"));
            returnList.Add(new Restaurant(90001778, "Jiko - The Cooking Place"));
            returnList.Add(new Restaurant(17736030, "Jiko Wine Tasting"));
            returnList.Add(new Restaurant(18107544, "Jock Lindsey's Hangar Bar"));
            returnList.Add(new Restaurant(90001780, "Joffrey's Handcrafted Smoothies at Disney Springs Marketplace"));
            returnList.Add(new Restaurant(90001562, "Joffrey's Handcrafted Smoothies at Disney Springs West Side"));
            returnList.Add(new Restaurant(214225, "Joy of Tea"));
            returnList.Add(new Restaurant(18185631, "Jungle Navigation Co. Ltd. Skipper Canteen"));
            returnList.Add(new Restaurant(16115734, "Kabuki Cafe"));
            returnList.Add(new Restaurant(16300748, "Katsura Grill"));
            returnList.Add(new Restaurant(90001784, "Kimonos"));
            returnList.Add(new Restaurant(108856, "Kimonos Lounge"));
            returnList.Add(new Restaurant(90001786, "Kona Cafe"));
            returnList.Add(new Restaurant(90001790, "Kona Island"));
            returnList.Add(new Restaurant(90001794, "Kringla Bakeri Og Kafe"));
            returnList.Add(new Restaurant(84804, "KRNR The Rock Station"));
            returnList.Add(new Restaurant(90001796, "Kusafiri Coffee Shop & Bakery"));
            returnList.Add(new Restaurant(90001345, "La Cantina de San Angel"));
            returnList.Add(new Restaurant(348023, "La Cava del Tequila"));
            returnList.Add(new Restaurant(214222, "Laguna Bar"));
            returnList.Add(new Restaurant(15525573, "La Hacienda de San Angel"));
            returnList.Add(new Restaurant(18134441, "The Land Cart"));
            returnList.Add(new Restaurant(16472580, "Landscape of Flavors"));
            returnList.Add(new Restaurant(17457762, "L'Artisan des Glaces"));
            returnList.Add(new Restaurant(248572, "Las Ventanas"));
            returnList.Add(new Restaurant(17480848, "Lava Lounge at Rainforest Cafe®"));
            returnList.Add(new Restaurant(90001800, "Leaning Palms"));
            returnList.Add(new Restaurant(90001802, "Leaping Horse Libations"));
            returnList.Add(new Restaurant(90001798, "Le Cellier Steakhouse"));
            returnList.Add(new Restaurant(90001328, "Les Halles Boulangerie-Patisserie"));
            returnList.Add(new Restaurant(90002394, "Les Vins des Chefs de France"));
            returnList.Add(new Restaurant(90001805, "Let's Go Slurpin'"));
            returnList.Add(new Restaurant(90001809, "Liberty Inn"));
            returnList.Add(new Restaurant(90001815, "Liberty Square Market"));
            returnList.Add(new Restaurant(90001819, "Liberty Tree Tavern"));
            returnList.Add(new Restaurant(108864, "Lobby Lounge"));
            returnList.Add(new Restaurant(90001827, "Lottawatta Lodge"));
            returnList.Add(new Restaurant(90001829, "Lotus Blossom Café"));
            returnList.Add(new Restaurant(90001831, "Lowtide Lou's"));
            returnList.Add(new Restaurant(90001833, "Luau Cove"));
            returnList.Add(new Restaurant(90002664, "The Lunching Pad"));
            returnList.Add(new Restaurant(15775832, "MacGUFFINS"));
            returnList.Add(new Restaurant(90002538, "Mahindi"));
            returnList.Add(new Restaurant(90002590, "Main Street Bakery"));
            returnList.Add(new Restaurant(293709, "Maji Pool Bar"));
            returnList.Add(new Restaurant(90001865, "Mama Melrose's Ristorante Italiano"));
            returnList.Add(new Restaurant(90002251, "The Mara"));
            returnList.Add(new Restaurant(90001869, "Mardi Grogs"));
            returnList.Add(new Restaurant(18807537, "Maria & Enzo's Ristorante"));
            returnList.Add(new Restaurant(18705412, "The Market at Ale & Compass"));
            returnList.Add(new Restaurant(90001875, "Martha's Vineyard"));
            returnList.Add(new Restaurant(90001879, "Maya Grill"));
            returnList.Add(new Restaurant(90002223, "Meadow Snack Bar"));
            returnList.Add(new Restaurant(255947, "Mickey's Backyard BBQ    "));
            returnList.Add(new Restaurant(90001307, "Mini Donuts at Disney's Blizzard Beach Water Park"));
            returnList.Add(new Restaurant(90001963, "Mizner's Lounge"));
            returnList.Add(new Restaurant(90001296, "Monsieur Paul"));
            returnList.Add(new Restaurant(17936194, "Morimoto Asia"));
            returnList.Add(new Restaurant(18427474, "Morimoto Asia Street Food"));
            returnList.Add(new Restaurant(90002604, "Muddy Rivers"));
            returnList.Add(new Restaurant(90001983, "Narcoossee's"));
            returnList.Add(new Restaurant(90001985, "Nine Dragons Restaurant"));
            returnList.Add(new Restaurant(18377778, "Nomad Lounge"));
            returnList.Add(new Restaurant(18394219, "Oasis Bar & Grill"));
            returnList.Add(new Restaurant(15494775, "Oasis Canteen"));
            returnList.Add(new Restaurant(90002606, "'Ohana"));
            returnList.Add(new Restaurant(90002006, "Olivia's Cafe"));
            returnList.Add(new Restaurant(18617840, "On the Green Grill"));
            returnList.Add(new Restaurant(90002008, "On the Rocks Pool Bar"));
            returnList.Add(new Restaurant(90002010, "Outer Rim"));
            returnList.Add(new Restaurant(18457125, "Paddlefish"));
            returnList.Add(new Restaurant(16018746, "The Paddock Grill"));
            returnList.Add(new Restaurant(343233, "Paradiso 37, Taste of the Americas"));
            returnList.Add(new Restaurant(90002610, "Pecos Bill Tall Tale Inn and Cafe"));
            returnList.Add(new Restaurant(90002024, "Pepper Market"));
            returnList.Add(new Restaurant(90002026, "Petals Pool Bar"));
            returnList.Add(new Restaurant(90002298, "Picabu"));
            returnList.Add(new Restaurant(17856782, "Pineapple Lanai"));
            returnList.Add(new Restaurant(90002618, "Pinocchio Village Haus"));
            returnList.Add(new Restaurant(90002032, "Pioneer Hall"));
            returnList.Add(new Restaurant(18758023, "Pirates & Pals Fireworks Dessert Voyage"));
            returnList.Add(new Restaurant(90002620, "Pizzafari"));
            returnList.Add(new Restaurant(18869927, "Pizza Ponte"));
            returnList.Add(new Restaurant(90002038, "Pizza Window"));
            returnList.Add(new Restaurant(18458041, "PizzeRizzo"));
            returnList.Add(new Restaurant(18039048, "P & J's Southern Takeout"));
            returnList.Add(new Restaurant(18475350, "Planet Hollywood Observatory"));
            returnList.Add(new Restaurant(91955, "Plaza Ice Cream Parlor"));
            returnList.Add(new Restaurant(90002670, "The Plaza Restaurant"));
            returnList.Add(new Restaurant(90002049, "Polar Pub"));
            returnList.Add(new Restaurant(18692523, "The Polite Pig"));
            returnList.Add(new Restaurant(18665177, "Pongu Pongu"));
            returnList.Add(new Restaurant(90001343, "Popcorn in Canada"));
            returnList.Add(new Restaurant(17517004, "Prince Eric’s Village Market"));
            returnList.Add(new Restaurant(248785, "Promenade Refreshments"));
            returnList.Add(new Restaurant(90002044, "Raglan Road™ Irish Pub and Restaurant"));
            returnList.Add(new Restaurant(90002440, "Rainforest Cafe® at Disney's Animal Kingdom"));
            returnList.Add(new Restaurant(90001873, "Rainforest Cafe® at Disney Springs Marketplace"));
            returnList.Add(new Restaurant(17564465, "Ravello"));
            returnList.Add(new Restaurant(90001409, "Refreshment Outpost"));
            returnList.Add(new Restaurant(90002672, "Refreshment Port"));
            returnList.Add(new Restaurant(90002068, "Restaurant Marrakesh"));
            returnList.Add(new Restaurant(90002632, "Restaurantosaurus"));
            returnList.Add(new Restaurant(90002073, "River Roost"));
            returnList.Add(new Restaurant(90002077, "Riverside Mill Food Court"));
            returnList.Add(new Restaurant(18386152, "Rivers of Light Dining Package"));
            returnList.Add(new Restaurant(248573, "Rix Sports Bar & Grill"));
            returnList.Add(new Restaurant(90002080, "Roaring Fork"));
            returnList.Add(new Restaurant(90002084, "Rose & Crown Dining Room"));
            returnList.Add(new Restaurant(90002086, "Rose & Crown Pub"));
            returnList.Add(new Restaurant(90002090, "Rosie's All-American Café"));
            returnList.Add(new Restaurant(18707496, "Safari Bar"));
            returnList.Add(new Restaurant(293704, "Sanaa"));
            returnList.Add(new Restaurant(15602781, "Sanaa Lounge"));
            returnList.Add(new Restaurant(90002100, "San Angel Inn Restaurante"));
            returnList.Add(new Restaurant(90002260, "The Sand Bar"));
            returnList.Add(new Restaurant(90002110, "Sassagoula Floatworks and Food Factory"));
            returnList.Add(new Restaurant(18665138, "Satu'li Canteen"));
            returnList.Add(new Restaurant(90002112, "Scat Cat's Club"));
            returnList.Add(new Restaurant(90002114, "Sci-Fi Dine-In Theater Restaurant"));
            returnList.Add(new Restaurant(109173, "Shula's Lounge"));
            returnList.Add(new Restaurant(90002122, "Shula's Steak House"));
            returnList.Add(new Restaurant(90002130, "Siestas Cantina"));
            returnList.Add(new Restaurant(90002134, "Silver Screen Spirits Pool Bar"));
            returnList.Add(new Restaurant(90002136, "Singing Spirits Pool Bar"));
            returnList.Add(new Restaurant(90002140, "Sleepy Hollow"));
            returnList.Add(new Restaurant(90002646, "The Smiling Crocodile"));
            returnList.Add(new Restaurant(17728113, "The Smokehouse"));
            returnList.Add(new Restaurant(90002146, "Snack Shack"));
            returnList.Add(new Restaurant(90002154, "Sommerfest"));
            returnList.Add(new Restaurant(17720675, "Spice Road Table"));
            returnList.Add(new Restaurant(90002168, "Splash Terrace"));
            returnList.Add(new Restaurant(17134590, "Splitsville Dining Room"));
            returnList.Add(new Restaurant(18422611, "Sprinkles"));
            returnList.Add(new Restaurant(17782688, "STARBUCKS® at Disney Springs Marketplace"));
            returnList.Add(new Restaurant(17559972, "STARBUCKS® at Disney Springs West Side"));
            returnList.Add(new Restaurant(18687557, "Stargazers Bar"));
            returnList.Add(new Restaurant(18177814, "Star Wars: A Galactic Spectacular Dessert Party at Disney's Hollywood Studios"));
            returnList.Add(new Restaurant(17957969, "STK Orlando"));
            returnList.Add(new Restaurant(90002602, "Storybook Treats"));
            returnList.Add(new Restaurant(90002190, "Sunshine Seasons"));
            returnList.Add(new Restaurant(90002656, "Sunshine Tree Terrace"));
            returnList.Add(new Restaurant(18699528, "Tables in Wonderland"));
            returnList.Add(new Restaurant(90002201, "Tambu Lounge"));
            returnList.Add(new Restaurant(90002203, "Tamu Tamu Refreshments"));
            returnList.Add(new Restaurant(90002205, "Tangierine Café"));
            returnList.Add(new Restaurant(18077015, "Taste Track"));
            returnList.Add(new Restaurant(18107545, "Tea Traders Cafe by Joffrey's"));
            returnList.Add(new Restaurant(221625, "Teppan Edo"));
            returnList.Add(new Restaurant(18752054, "Terralina Crafted Italian - Coming Soon!"));
            returnList.Add(new Restaurant(90002642, "Terra Treats"));
            returnList.Add(new Restaurant(90002217, "Territory Lounge"));
            returnList.Add(new Restaurant(90001412, "Test Track Cool Wash"));
            returnList.Add(new Restaurant(18076996, "Thirsty River Bar & Trek Snacks"));
            returnList.Add(new Restaurant(18551707, "Tiana's  Riverboat Party - Ice Cream Social & Viewing Party"));
            returnList.Add(new Restaurant(18069632, "Tiffins"));
            returnList.Add(new Restaurant(90002274, "Todd English's bluezoo"));
            returnList.Add(new Restaurant(109179, "Todd English's bluezoo Lounge"));
            returnList.Add(new Restaurant(90001313, "The To-Go Cart"));
            returnList.Add(new Restaurant(221626, "Tokyo Dining"));
            returnList.Add(new Restaurant(90002668, "Tomorrowland Terrace Restaurant"));
            returnList.Add(new Restaurant(90002678, "Tony's Town Square Restaurant"));
            returnList.Add(new Restaurant(90001473, "Tortuga Tavern"));
            returnList.Add(new Restaurant(18050972, "Trader Sam's Grog Grotto"));
            returnList.Add(new Restaurant(18120859, "Trader Sam's Tiki Terrace"));
            returnList.Add(new Restaurant(90002287, "Trail's End Restaurant"));
            returnList.Add(new Restaurant(17851099, "Trattoria al Forno"));
            returnList.Add(new Restaurant(293563, "T-REX ™"));
            returnList.Add(new Restaurant(90002614, "Trilo-Bites"));
            returnList.Add(new Restaurant(17928418, "The Trolley Car Café"));
            returnList.Add(new Restaurant(90002300, "Tune-In Lounge"));
            returnList.Add(new Restaurant(98575, "The Turf Club Bar and Grill"));
            returnList.Add(new Restaurant(90002266, "The Turf Club Lounge"));
            returnList.Add(new Restaurant(90002309, "Turtle Shack Poolside Snacks"));
            returnList.Add(new Restaurant(90002686, "Tusker House Restaurant"));
            returnList.Add(new Restaurant(16526362, "Tutto Gusto Wine Cellar"));
            returnList.Add(new Restaurant(220739, "Tutto Italia Ristorante"));
            returnList.Add(new Restaurant(90002324, "Typhoon Tilly's"));
            returnList.Add(new Restaurant(90002326, "UK Beer Cart"));
            returnList.Add(new Restaurant(90002332, "Uzima Springs Pool Bar"));
            returnList.Add(new Restaurant(15525574, "Via Napoli Ristorante e Pizzeria"));
            returnList.Add(new Restaurant(90002336, "Victoria & Albert's"));
            returnList.Add(new Restaurant(17736021, "Victoria & Albert's Chef's Table Dinner"));
            returnList.Add(new Restaurant(17736032, "Victoria & Albert's Dinner Queen Victoria Room"));
            returnList.Add(new Restaurant(90002344, "Victoria Falls Lounge"));
            returnList.Add(new Restaurant(18099281, "Vivoli il Gelato"));
            returnList.Add(new Restaurant(18070749, "Wanyama Safari"));
            returnList.Add(new Restaurant(90002364, "Warming Hut"));
            returnList.Add(new Restaurant(15921468, "Warung Outpost"));
            returnList.Add(new Restaurant(278252, "The Wave Lounge"));
            returnList.Add(new Restaurant(266442, "The Wave... of American Flavors"));
            returnList.Add(new Restaurant(90002688, "Westward Ho"));
            returnList.Add(new Restaurant(90002374, "Wetzel's Pretzels at Disney Springs Marketplace"));
            returnList.Add(new Restaurant(17485537, "Wetzel's Pretzels at Disney Springs West Side"));
            returnList.Add(new Restaurant(90002376, "Whispering Canyon Cafe"));
            returnList.Add(new Restaurant(18667615, "Wine Bar George - Coming Early 2018"));
            returnList.Add(new Restaurant(90002400, "Wolfgang Puck® Express at Disney Springs Marketplace"));
            returnList.Add(new Restaurant(18904173, "Woody's Lunch Box - Opening Summer 2018!"));
            returnList.Add(new Restaurant(90002408, "World Premiere Food Court"));
            returnList.Add(new Restaurant(90002412, "Yachtsman Steakhouse"));
            returnList.Add(new Restaurant(241676, "Yak & Yeti™ Local Food Cafes"));
            returnList.Add(new Restaurant(247503, "Yak & Yeti™ Quality Beverages"));
            returnList.Add(new Restaurant(215686, "Yak & Yeti™ Restaurant"));
            returnList.Add(new Restaurant(18430303, "YeSake"));
            returnList.Add(new Restaurant(90002416, "Yorkshire County Fish Shop"));

            return returnList;
        }
    }


}
